# Generated by Django 4.1.9 on 2023-06-02 09:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(default='+375 (29) xxx-xx-xx', max_length=20, validators=[django.core.validators.RegexValidator(regex='^+375 \\(29\\) \\d{3}-\\d{2}-\\d{2}$')])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('adress', models.CharField(default='Gikalo, 9', max_length=100, validators=[django.core.validators.RegexValidator(regex='^+375 \\(29\\) \\d{3}-\\d{2}-\\d{2}$')])),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('number', models.CharField(default='+375 (29) xxx-xx-xx', max_length=20, validators=[django.core.validators.RegexValidator(regex='^+375 \\(29\\) \\d{3}-\\d{2}-\\d{2}$')])),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Doctor_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Doc_Category',
                'verbose_name_plural': 'Doc_Categories',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(max_length=30)),
                ('price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['procedure', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_in_shedule', to='CosmetologyApp.client')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_in_shedule', to='CosmetologyApp.doctor')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_in_shedule', to='CosmetologyApp.room')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_in_shedule', to='CosmetologyApp.service')),
            ],
            options={
                'verbose_name': 'Shedule',
                'verbose_name_plural': 'Shedules',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_servise', to='CosmetologyApp.service')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['service', 'count'],
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_category', to='CosmetologyApp.doctor_category'),
        ),
        migrations.AddField(
            model_name='client',
            name='doctor',
            field=models.ManyToManyField(blank=True, related_name='doctor_for_client', to='CosmetologyApp.doctor'),
        ),
        migrations.AddField(
            model_name='client',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='servise_for_client', to='CosmetologyApp.service'),
        ),
    ]
