# Generated by Django 4.1.9 on 2023-06-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0002_remove_client_adress_alter_doctor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name', 'number'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
    ]
