# Generated by Django 4.1.9 on 2023-06-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0004_alter_doctor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='client',
            name='service',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='category',
        ),
        migrations.AlterField(
            model_name='shedule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shedule_service', to='CosmetologyApp.service'),
        ),
    ]
