# Generated by Django 4.1.9 on 2023-06-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0006_alter_shedule_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
