# Generated by Django 4.1.9 on 2023-06-03 20:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0007_alter_shedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
