# Generated by Django 4.1.9 on 2023-06-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0008_alter_shedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
