# Generated by Django 4.1.9 on 2023-06-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0010_alter_client_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
