# Generated by Django 4.1.9 on 2023-06-04 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0011_alter_client_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(help_text='+375 (29) xxx-xx-xx', max_length=20, validators=[django.core.validators.RegexValidator(regex='^+375 \\(29\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
