# Generated by Django 4.1.9 on 2023-06-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0012_alter_client_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='birth_date',
        ),
    ]
