# Generated by Django 4.1.9 on 2023-06-04 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0016_alter_service_options_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(default='0.00', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(150.0)]),
        ),
    ]
