# Generated by Django 4.1.9 on 2023-09-13 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0018_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(default='0.00', validators=[django.core.validators.MinValueValidator(100.0), django.core.validators.MaxValueValidator(1500.0)]),
        ),
    ]
