# Generated by Django 4.1.9 on 2023-09-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0020_alter_vacancy_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='enter Promocode', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
