# Generated by Django 4.1.9 on 2023-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0022_promocode_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='start_date',
            field=models.DateField(),
        ),
    ]
