# Generated by Django 4.1.9 on 2023-09-13 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0028_alter_shedule_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(help_text='enter reviewer', max_length=50)),
                ('rate', models.PositiveIntegerField(help_text='enter rate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField(help_text='enter review text')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
