# Generated by Django 4.1.9 on 2023-09-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmetologyApp', '0029_rewiew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewiew',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
